### ISSUE TITLE
web socket connection closing with "unexpected EOF"

### ISSUE THREAD

**Issue by jmanian** [zerobotlabs/relax#17]
I'm not sure if this is a code issue—perhaps it's behaving as expected—apologies in advance if that's the case. But this is a problem that I'm having with an instance of relax that I'm running on Heroku (deployed using the button).

We've had this instance of relax running for about 6 weeks without incident, but in the last 2 or 3 days we've had a sudden influx of the below error:

`time="2016-06-04T20:24:54Z" level=error msg="error reading message from slack websocket connection" error="websocket: close 1006 unexpected EOF" team=TXXXXXXXX`

When this happens the web socket with the particular team closes. I'm able to reopen it by restarting the app. It's not confined to one particular team—it happens with any and all teams.

Any ideas? Maybe something weird happening with the Slack RTM API in the last couple days?

**Comment by arunthampi** [comment]
hi @jmanian thanks for reporting this, I've been observing this on my install of relax too and am investigating a fix, will let you know once I have updates.

**Comment by arunthampi** [comment]
I have a fix in this branch: https://github.com/zerobotlabs/relax/tree/reconnect-on-eof which I've deployed to production one of my apps and will be monitoring over the next couple of days. It basically reconnects in case of an error.

Can you please deploy to your app and report back if it does reconnect on failure? thanks!

**Comment by jmanian** [comment]
Awesome thanks, and I'm glad to hear it wasn't just us getting the eof. I just deployed your fix to our app and I will be monitoring. Although we haven't seen any eof in a couple days, so I'm not sure we'll be able to tell. Will the error still surface in the logs if an eof occurs, or will it be suppressed now?

**Comment by arunthampi** [comment]
It will still show up, but it should reconnect when that happens and you should see this log immediately after: https://github.com/zerobotlabs/relax/blob/reconnect-on-eof/slack/client.go#L545-L547

thanks! please let me know.

**Comment by arunthampi** [comment]
@jmanian just checking if you've encountered this problem again. I have been monitoring and haven't seen anything untoward. Let me know!

**Comment by jmanian** [comment]
We actually did receive a handful of "1006 unexpected EOF" over the weekend, and the automatic reconnect seems to be working. But there is actually a new error now that shows up immediately after the reconnect. Here's how it looks in the logs:

```
time="2016-06-12T05:18:24Z" level=error msg="error reading message from slack websocket connection" error="websocket: close 1006 unexpected EOF" team=TXXXXXXXX
time="2016-06-12T05:18:24Z" level=info msg="restarting client from within the read loop" team=TXXXXXXXX
time="2016-06-12T05:18:25Z" level=error msg="starting slack client" error="migration_in_progress" team=TXXXXXXXX
```

Any idea what this is about?

**Comment by arunthampi** [comment]
Great will merge this in master. The other bug message that you described sounds like it is this: https://api.slack.com/events/team_migration_started, will raise another issue to fix it.

**Comment by arunthampi** [comment]
closed by https://github.com/zerobotlabs/relax/pull/19
